services:
  opensearch:
    image: opensearchproject/opensearch:latest
    container_name: opensearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - "OPENSEARCH_JAVA_OPTS=-Xms4g -Xmx4g"
      - DISABLE_SECURITY_PLUGIN=true
    volumes:
      - os_data:/usr/share/opensearch/data
    ports:
      - 9200:9200

  opensearch-dashboards:
    image: opensearchproject/opensearch-dashboards:latest
    container_name: dashboards
    restart: unless-stopped
    environment:
      - 'OPENSEARCH_HOSTS=["http://opensearch:9200"]'
      - DISABLE_SECURITY_DASHBOARDS_PLUGIN=true
    ports:
      - 5601:5601
    depends_on:
      - opensearch
      
  neo4j:
    image: neo4j:latest
    container_name: neo4j-server
    restart: unless-stopped
    ports:
      - "7474:7474" # HTTP Browser
      - "7687:7687" # Bolt (Driver connection)
    environment:
      - NEO4J_AUTH=neo4j/password
      - NEO4J_dbms_security_procedures_unrestricted=apoc.*
      - NEO4J_dbms_security_procedures_allowlist=apoc.*
      - NEO4J_apoc_import_file_enabled=true
      - NEO4J_apoc_import_file_useneo4jconfig=true
      - NEO4J_PLUGINS=["apoc"]
    volumes:
      - neo4j_data:/data
      - neo4j_logs:/logs

volumes:
  os_data:
  neo4j_data:
  neo4j_logs:
